### ISSUE TITLE
improve workshop for targeted audience 

### ISSUE THREAD

**Issue by Shimwell** [ukaea/openmc_workshop#10]
There are a few ways the workshop can be improved to maximise the learning of fusion neutronics

First add fusion context and learning points to the tasks, perhaps in the form of a task conclusion

Trim the tasks to less time is spent geometry making

**Comment by billingsley-john** [comment]
I have reduced the number of tasks relating to geometry making. #15

**Comment by Shimwell** [comment]
I have found a method of highlighting the conclusions using color which is compatible with the github mark down https://stackoverflow.com/questions/11509830/how-to-add-color-to-githubs-readme-md-file

**Comment by Shimwell** [comment]
> I have reduced the number of tasks relating to geometry making. #15

I can see that the amount of geometry making in task 2 is now reduced, thanks for that. 

Is this also transferred to the colab version?

**Comment by Shimwell** [comment]
I spotted that task 2 was asking participants to make some geometry and the view it in 3d and then do the same again. I have removed this duplication so there are now only 4 activities in task 2 while covering the same set learning objectives :-)

**Comment by Shimwell** [comment]
The list / index of tasks at the start of the readme has now be split into Core and Optional. 

Also allocated time for each task has been added to the index 

![Screenshot from 2020-01-07 09-37-53](https://user-images.githubusercontent.com/8583900/71885041-6d971d80-3131-11ea-9ca6-8dbbb36af04b.png)

**Comment by Shimwell** [comment]
Added timings to the slide show to keep participants on track

![Screenshot from 2020-01-07 12-03-58](https://user-images.githubusercontent.com/8583900/71894333-ddaf9e80-3145-11ea-9aeb-d700e43add7d.png)

**Comment by Shimwell** [comment]
Workshop delivered successfully, closing issue.
