### ISSUE TITLE
Parametric plasma source input units should be meters

### ISSUE THREAD

**Issue by DanShort12** [ukaea/openmc_workshop#125]
It looks like length dimensions are being passed into the parametric plasma source in task 12 in centimeters:

```python
plasma_params = {
    "elongation": 2.9,
    "ion_density_origin": 1.09e20,
    "ion_density_peaking_factor": 1,
    "ion_density_pedestal": 1.09e20,
    "ion_density_separatrix": 3e19,
    "ion_temperature_origin": 45.9,
    "ion_temperature_peaking_factor": 8.06,
    "ion_temperature_pedestal": 6.09,
    "ion_temperature_separatrix": 0.1,
    "major_radius": 1.9*100,
    "minor_radius": 1.118*100,
    "pedestal_radius": 0.8 *  1.118*100,
    "plasma_id": 1,
    "shafranov_shift": 0.44789,
    "triangularity": 0.270,
    "ion_temperature_beta": 6,
}
```

As described on the [parametric plasma source](https://github.com/makeclean/parametric-plasma-source), the input units should be meters, so I suggest the above code block should be:

```python
plasma_params = {
    "elongation": 2.9,
    "ion_density_origin": 1.09e20,
    "ion_density_peaking_factor": 1,
    "ion_density_pedestal": 1.09e20,
    "ion_density_separatrix": 3e19,
    "ion_temperature_origin": 45.9,
    "ion_temperature_peaking_factor": 8.06,
    "ion_temperature_pedestal": 6.09,
    "ion_temperature_separatrix": 0.1,
    "major_radius": 1.9,
    "minor_radius": 1.118,
    "pedestal_radius": 0.8 *  1.118,
    "plasma_id": 1,
    "shafranov_shift": 0.44789,
    "triangularity": 0.270,
    "ion_temperature_beta": 6,
}
```

I believe this relates to makeclean/parametric-plasma-source#14, raised by @qingfengxia as in this case particles will be very likely to be generated with starting points outside of the defined geometry. Some of the comments around the PR to introduce the serialisation (makeclean/parametric-plasma-source#8) might have caused some confusion here, but we settled on input length units of meters with a conversion to cm in the OpenMC sampling to allow for portability.

**Comment by Shimwell** [comment]
Ah yes, I can update this. Thanks for reporting

**Comment by Shimwell** [comment]
confirmed that the tasks have been updated
