### ISSUE TITLE
imporved install videos

### ISSUE THREAD

**Issue by Shimwell** [ukaea/openmc_workshop#255]
adding some specific os video install videos, here are some icons for the updated readme.

![Screenshot from 2021-04-08 10-47-59](https://user-images.githubusercontent.com/8583900/114006504-6725b300-9858-11eb-905f-b7b2f26a0113.png)

![linux](https://user-images.githubusercontent.com/8583900/114006368-4b221180-9858-11eb-95bb-3064683bec71.png)

![500px-Windows_logo_-_2012 svg](https://user-images.githubusercontent.com/8583900/114006280-3b0a3200-9858-11eb-9470-1bd11a4858d2.png)

**Comment by Shimwell** [comment]
mac os mojave video is also in the works

**Comment by Shimwell** [comment]
![Screenshot from 2021-04-08 11-00-23](https://user-images.githubusercontent.com/8583900/114008054-c9cb7e80-9859-11eb-8e07-32e95c600667.png)
![Screenshot from 2021-04-08 10-56-14](https://user-images.githubusercontent.com/8583900/114008108-d3ed7d00-9859-11eb-8bb5-0c19ce775015.png)

**Comment by Shimwell** [comment]
![Screenshot from 2021-04-09 12-13-12](https://user-images.githubusercontent.com/8583900/114172031-05834880-992d-11eb-8277-5a6cda2b5e12.png)

**Comment by shimwell** [comment]
all done and in the main branch now
