### ISSUE TITLE
neutronics_model.simulate() issue

### ISSUE THREAD

**Issue by squang** [ukaea/openmc_workshop#260]
Task 11 and task 12 have the same error with "neutronics_model.simulate() ". The error value is:

> ValueError: ('the method using in create_neutronics_geometry                 should be either ppp, trelis, pymoab or None.', None)

**Comment by shimwell** [comment]
@squang thanks for reporting this issue.

There have been so many improvements / changes in the underlying codes that a bit of a rewrite is needed to fix this one.

Are you able to try the new version here

```bash
docker pull ghcr.io/fusion-energy/neutronics-workshop
```
```bash
docker run -p 8888:8888 ghcr.io/fusion-energy/neutronics-workshop
```

**Comment by squang** [comment]
@Shimwell Thank you so much for your response.
Tasks 11 and 12 now work flawlessly.

I start moving from using other transport codes to OpenMC, and your workshop is super helpful. Thank you so much!
