### ISSUE TITLE
MPI Configuration in Dockerfile

### ISSUE THREAD

**Issue by oliverkellyukaea** [ukaea/openmc_workshop#3]
Not sure if building an mpi-enabled version of OpenMC works in the current iteration of the Dockerfile. OpenMC documentation says the cxx compiler needs to be mpicxx, which isn't defined currently in the Dockerfile. Additionally, the ENV FC=mpif90 line can probably be removed now the codebase is no longer written in Fortran.

**Comment by Shimwell** [comment]
I guess this line needs changing 

RUN apt install --yes mpich libmpich-dev

to 

RUN apt install --yes mpich

**Comment by Shimwell** [comment]
Dockerfiles have been rewritten :-)
