### ISSUE TITLE
task_1: other lead isotopes already added to the plot 

### ISSUE THREAD

**Issue by DeclanMorbey** [ukaea/openmc_workshop#77]
In Task_1 we have:

"Try adding the other lead isotopes to the plot (Pb207 and Pb208)."

however this is task is already complete within the 1_example_isotope_plot.py.

**Comment by billingsley-john** [comment]
fixed in repository. docker image must now be rebuilt

**Comment by billingsley-john** [comment]
images rebuilt and pushed to dockerhub
